# 插件版本（不知道这是什么，不要随意修改）
version: 1.0-SNAPSHOT
# 死亡判定高度
height: 60
# 比赛时间，默认5分钟
time: 300
# 场馆玩家传送位置
world: world
stadium:
  # 第一玩家位置
  -
    x: 0.0
    y: 60.0
    z: 0.0
  # 第二玩家位置
  -
    x: -1.0
    y: 60.0
    z: 0.0
  # 第三玩家位置
  -
    x: 0.0
    y: 60.0
    z: -1.0
  # 第四玩家位置
  -
    x: -1.0
    y: 60.0
    z: -1.0
# 死亡后传送位置
grave:
  x: 0.0
  y: 70.0
  z: 0.0