name: icesumo
version: '1.0-SNAPSHOT'
author: "AndyShen2006"
main: top.andyshen2006.icesumo.Icesumo
api-version: '1.21'
commands:
  start:
    description: "开始比赛"
    usage: "/start"
  terminate:
    description: "终止比赛"
    usage: "/terminate"
  showinfo:
    description: ""
  checkin:
    description: "检录"
    usage: "/checkin"
  checkinlist:
    description: "输出检录列表"
    usage: "/checkinlist"
  uncheckin:
    description: "取消检录"
    usage: "/uncheckin"
  editheight:
    description: "修改判定高度"
  editpos:
    description: "修改场馆位置"
  editgrave:
    description: "修改判定高度"
  testdelay:
    description: ""
  testedit:
    description: ""
  testlisten:
    description: ""
  testkit:
    description: ""