name: Icesumo Plugin Automatic Build

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: List build files
      run: ls -la build/libs/
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plugin-jars
        path: build/libs/*.jar
